#!/bin/sh

###############################################################
#following are remote repo account,this list can be modified. #
#                                                             #
coding=https://git.coding.net/cruiser_ysw                     #
github=https://github.com/34985086                            #
oschina=https://git.oschina.net/cruiser_ysw                   #
csdn=https://code.csdn.net/cruiser_ysw                        #
###############################################################

#
repoName=$(basename $(pwd))

for account in $coding $github $oschina $csdn
do
    url=$account/$repoName.git

    echo "git push to $url"
    git push $url master # use default (master) branch
    echo ""
done

  
